### ISSUE TITLE
FAHControl on Ubuntu

### ISSUE THREAD

**Issue by rotten** [FoldingAtHome/fah-control#20]
I tried installing the debian package from the folding at home site first.  I'm running Ubuntu 17.10.  Unfortunately it complains about missing the python-support package, which hasn't been a part of Ubuntu for at least 2 1/2 years and will never come back.  Searching, I found several other people who ran into this issue when 16.04 first came out.  I haven't found any workarounds for the 2017 versions of Ubuntu.

So next I thought I'd try running it from this repo.  I installed the required python packages listed in the Read.me, and after cloning, tried this:

```
$  python ./FAHControl
Traceback (most recent call last):
  File "./FAHControl", line 25, in <module>
    from fah import FAHControl, load_fahcontrol_db
  File "/home/rotten/src/fah-control/fah/__init__.py", line 24, in <module>
    from Version import *
ImportError: No module named Version

```
The above error is when I use Python 2.

If I try it with python3 I get a different error that highlights this is definitely old python version 2 code and that python3 is not what I'm supposed to be using.

```
$  python3 ./FAHControl
  File "./FAHControl", line 57
    if sock.recv(1024).strip() == 'OK': print 'Ok'
                                                 ^
SyntaxError: invalid syntax
```
So the next thing to try was to build it:

```
$  python ./setup.py build
dir = .
running build
running build_py
copying fah/FAHControl_glade.py -> build/lib.linux-x86_64-2.7/fah
running egg_info
writing requirements to FAHControl.egg-info/requires.txt
writing FAHControl.egg-info/PKG-INFO
writing top-level names to FAHControl.egg-info/top_level.txt
writing dependency_links to FAHControl.egg-info/dependency_links.txt
reading manifest file 'FAHControl.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'FAHControl.egg-info/SOURCES.txt'
running build_scripts
```
That looked like it worked ok.   However, I get the same "Version" error when I cd into build/scripts-2.7 and try to run the FAHControl that the build script dropped in there.

There is no Version.py.
I noticed that setup.py references it too, but only if version.txt is missing... (which it is).   So I'm somewhat surprised the build script didn't complain.

I'd like to run FAHControl on my Ubuntu systems.  I have two of them with very new, very nice GPU boards and a bunch of the latest cores and ram.  I'd rather do FAH than bitcoin mining or SETI processing, but getting this piece to work is not so obvious.  The client appears to be running ok.

Any suggestions?

**Comment by jcoffland** [comment]
As a quick fix you could edit ``FAHControl`` and replace the top line with ``#!/usr/bin/env python2``.

**Comment by jcoffland** [comment]
I've modified the script so that it will explicitly call python2 in future releases.

**Comment by rotten** [comment]
I did a git pull and confirmed the edit you described.  No luck.  The same missing Version error.

**Comment by jcoffland** [comment]
It doesn't work like that.  You have to build and install the package.

**Comment by rotten** [comment]
ok, gotcha.

`python2 ./setup.py build`
worked fine.

`sudo python2 ./setup.py install`
fails with this:

```
Installed /usr/local/lib/python2.7/dist-packages/FAHControl-0.0.0-py2.7.egg
Processing dependencies for FAHControl==0.0.0
Searching for gtk2>=2.14.0
Reading https://pypi.python.org/simple/gtk2/
Couldn't find index page for 'gtk2' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for gtk2>=2.14.0
error: Could not find suitable distribution for Requirement.parse('gtk2>=2.14.0')
```

I have all of these GTK2 components installed on my system already:
```
$  dpkg -l | grep -i gtk2
ii  gtk2-engines:amd64                         1:2.20.2-3ubuntu1                           amd64        theme engines for GTK+ 2.x
ii  gtk2-engines-aurora                        1.5.1-4                                     amd64        Aurora gtk+-2.0 theme engine
ii  gtk2-engines-blueheart                     0.20070123-0ubuntu2                         all          Blueheart GTK+ 2.x Theme
ii  gtk2-engines-cleanice                      2.4.1-3                                     amd64        CleanIce themes for GTK+ 2.x
ii  gtk2-engines-equinox                       1.50-0ubuntu4                               amd64        Equinox GTK+ theme engine
ii  gtk2-engines-magicchicken                  1.1.1-9                                     amd64        Magic Chicken themes for GTK+ 2.x
ii  gtk2-engines-murrine:amd64                 0.98.2-0ubuntu5                             amd64        cairo-based gtk+-2.0 theme engine
ii  gtk2-engines-nodoka                        0.7.2-0ubuntu3                              amd64        Nodoka theme engine for GTK+ 2.x
ii  gtk2-engines-oxygen:amd64                  1.4.6-1ubuntu1                              amd64        Oxygen widget theme for GTK+-based applications
ii  gtk2-engines-pixbuf:amd64                  2.24.31-2ubuntu1                            amd64        pixbuf-based theme for GTK+ 2.x
ii  gtk2-engines-qtcurve:amd64                 1.8.18+git20160320-3d8622c-5build1          amd64        QtCurve widget style for applications based on GTK+ 2.x
ii  gtk2-engines-sugar:amd64                   0.110.0-1                                   amd64        Sugar Learning Platform - GTK+ 2.x theme engine
ii  gtk2-engines-wonderland                    1.0-11                                      amd64        Wonderland theme for GTK+-2.0
ii  gtk2-engines-xfce                          3.2.0-2                                     amd64        GTK+-2.0 theme engine for Xfce
ii  libcheese-gtk25:amd64                      3.26.0-0ubuntu1                             amd64        tool to take pictures and videos from your webcam - widgets
ii  libgtk2-perl                               2:1.24992-1build1                           amd64        Perl interface to the 2.x series of the Gimp Toolkit library
ii  libgtk2.0-0:amd64                          2.24.31-2ubuntu1                            amd64        GTK+ graphical user interface library
ii  libgtk2.0-bin                              2.24.31-2ubuntu1                            amd64        programs for the GTK+ graphical user interface library
ii  libgtk2.0-cil                              2.12.40-2                                   amd64        CLI binding for the GTK+ toolkit 2.12
ii  libgtk2.0-common                           2.24.31-2ubuntu1                            all          common files for the GTK+ graphical user interface library
ii  libgtk2.0-dev                              2.24.31-2ubuntu1                            amd64        development files for the GTK+ library
ii  libunity-gtk2-parser0:amd64                0.0.0+17.10.20170817-0ubuntu1               amd64        GtkMenuShell to GMenuModel parser
ii  overlay-scrollbar-gtk2:amd64               0.2.17.1+16.04.20151117-0ubuntu2            amd64        GTK 2 module for overlay scrollbars
ii  python-gtk2                                2.24.0-5.1ubuntu1                           amd64        Python bindings for the GTK+ widget set
ii  python-gtk2-dev                            2.24.0-5.1ubuntu1                           all          GTK+ bindings: devel files
ii  python-gtk2-doc                            2.24.0-5.1ubuntu1                           all          Python bindings for the GTK+ widget set - documentation
ii  unity-gtk2-module:amd64                    0.0.0+17.10.20170817-0ubuntu1               amd64        GtkMenuShell D-Bus exporter
ii  yuyo-gtk-theme                             0.3                                         all          Yuyo GTK2 and GTK3 Theme
```

All of them are at the latest versions.  They look like they are version 2.14 or newer.

If I understand the error, it is actually going off system and looking for a gtk2 package on pypi.python.org/simple - and there isn't one there.

I double checked what is on my system already:

```
$  python2
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygtk
>>> pygtk._get_available_versions()
{'2.0': '/usr/lib/python2.7/dist-packages/gtk-2.0'}
>>> 

$  dpkg -S /usr/lib/python2.7/dist-packages/gtk-2.0
python-glade2, python-gobject-2, python-gtk2: /usr/lib/python2.7/dist-packages/gtk-2.0

$  dpkg -l python-gtk2
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                   Version                  Architecture             Description
+++-======================================-========================-========================-==================================================================================
ii  python-gtk2                            2.24.0-5.1ubuntu1        amd64                    Python bindings for the GTK+ widget set

```

I'm not sure what I'm actually missing.

**Comment by jcoffland** [comment]
I just checked in a minor change that allowed the following procedure to work for me.

In the ``fah-control`` source directory:

```
scons package
sudo dpkg -i deb_dist/fahcontrol_7.4.17-1_all.deb
sudo apt --fix-broken install
```

The last command was needed to fix missing dependencies.

**Comment by rotten** [comment]
Before "scons package" would work I had to:

```
sudo apt install scons
git clone https://github.com/CauldronDevelopmentLLC/cbang.git
git clone https://github.com/FoldingAtHome/fah-client-version.git

mkdir build
export BUILD_ROOT=/path/to/build_dir
export CBANG_HOME=/path/to/cbang-clone_dir
export FAH_CLIENT_VERSION_HOME=/path/to/fah-client-version-clone_dir
```

However, I'm stuck trying to figure out how RULES_BINARY_ALL_TARGET gets set and what it is supposed to be in this case.  I tried a couple of possibilities as an environment variable, but I don't think that is the trick here.

```
$  scons package
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
python setup.py --command-packages=stdeb.command bdist_deb
dir = .
running bdist_deb
running sdist_dsc
running egg_info
writing requirements to FAHControl.egg-info/requires.txt
writing FAHControl.egg-info/PKG-INFO
writing top-level names to FAHControl.egg-info/top_level.txt
writing dependency_links to FAHControl.egg-info/dependency_links.txt
reading manifest file 'FAHControl.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'FAHControl.egg-info/SOURCES.txt'
Traceback (most recent call last):
  File "setup.py", line 123, in <module>
    **extra_opts)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/stdeb/command/bdist_deb.py", line 22, in run
    self.run_command('sdist_dsc')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/stdeb/command/sdist_dsc.py", line 27, in run
    debinfo = self.get_debinfo()
  File "/usr/lib/python2.7/dist-packages/stdeb/command/common.py", line 226, in get_debinfo
    allow_virtualenv_install_location=self.allow_virtualenv_install_location,
  File "/usr/lib/python2.7/dist-packages/stdeb/util.py", line 1102, in __init__
    RULES_BINARY_ALL_TARGET%self.__dict__ + \
NameError: global name 'RULES_BINARY_ALL_TARGET' is not defined
scons: *** [deb_dist] Error 1
scons: building terminated because of errors.
```

**Comment by jcoffland** [comment]
The error is in ``/usr/lib/python2.7/dist-packages/stdeb/util.py`` This is part of your ``stdeb`` install.  Looks like it's installed incorrectly.  On my system, ``RULES_BINARY_ALL_TARGET`` is defined in ``stdeb/util.py``.  I'm not quite sure how I installed stdeb but it's in ``/usr/local/`` rather than ``/usr/``.  In short, your ``stdeb`` install has a bug.

**Comment by jreindel** [comment]
I am having this same issue. I'm not quite following your last point however.
`echo $RULES_BINARY_ALL_TARGET`
returns blank.
What should it be set to?

**Comment by gordonbb** [comment]
Mr. Coffland,

Thanks for your continued work on this project. While I understand that F@H will have to find funds to port FAHControl to Python3 I hope this will happen at some point in the future.

I've been building a Build Guide for Folding at Home on Ubuntu 18.0.4.3 LTS Desktop and have discovered that to get FAHControl working staying in the Ubuntu ecosystem all that is needed is:

```
sudo apt install python dh-python python-gnome2﻿﻿
wget https://download.foldingathome.org/releases/public/release/fahcontrol/debian-stable-64bit/v7.5/fahcontrol_7.5.1-1_all.deb﻿
sudo dpkg -i fahcontrol_7.5.1-1_all.deb﻿
```

**Comment by ipkh** [comment]
What needs to be done as far as converting to python 3?  Python 2 is no longer included in Ubuntu going forward and the new lts release 20.04 does not and will not have it available. Could the clients web control be modified to have some of the fahcontrol options?  It can already write out the config.xml for user details.  A way to enable GPU folding on linux via the web control would be nice if fahcontrol isn't likely to get converted to gtk3 and python3.

**Comment by msangel** [comment]
because of missing py2 libraries I cannot install it even on 19.10

Python2 end is closer than you think.

**Comment by ipkh** [comment]
Ubuntu 18.04 is the latest version with python 2 and gtk2 support.  2 more years till end of support.  Gtk2 and python2 are no longer developed.  The Gnome folks loved to gtk3 to coincide with Gnome Desktop 3.  Python has moved to Python version 3 and have officially ended python2 security updates.
The one downside of linux is the ever evolving libraries and interfaces.

**Comment by jcoffland** [comment]
FYI, a new client is in the works that will solve this.

**Comment by bb30994** [comment]
Will that new client also work on a Linux distro that still has python2 rather than python3?

**Comment by ipkh** [comment]
Any moderately maintained distribution will have python 3 available in addition to python 2.  As they are not directly compatible many distributions package both.  Once the python and interface are updated everything should be fine.  Though I think the openssl implementation needs to be updated as well.  I currently have to install an extra compatibility version for it to work.
Thanks for letting us know an updated client is in the works. The computation is almost 20% faster on linux and it is a bummer to be jumping through do many hoops to enable GPU folding on linux.

**Comment by bb30994** [comment]
I think your assumption of "moderately maintained" is a weak one.  They distribute LTS versions for a reason ... and that means we can expect systems which are not "moderately maintained" at least until Ubuntu announces that the LTS version is no longer supported.
https://wiki.ubuntu.com/LTS
https://ubuntu.com/about/release-cycle

**Comment by ipkh** [comment]
Bruce,

Python3 is not new and goes back to Ubuntu 16.04 .  It is widely available and Ubuntu is just an easy example.

**Comment by ttepatti** [comment]
At this point, Python 2 has officially been depreciated. Are there any plans to support Python 3 in the future?

**Comment by bb30994** [comment]
Of course, but we try to maintain backward compatibility, the issue is more complex than requiring everybody running a stable (and maybe long-term compatible) OS

A new client is being worked on, but there's no ETA.

**Comment by itsthejoker** [comment]
@jcoffland Do you know who can update the documentation here: https://foldingathome.org/support/faq/installation-guides/linux/? It still points to fah-control that cannot be installed; that's probably why there's been recent activity on this issue.

**Comment by eiglow** [comment]
Trying to run `python FAHControl.py`, I get the following:
```
Traceback (most recent call last):
  File "FAHControl", line 25, in <module>
    from fah import FAHControl, load_fahcontrol_db
  File "/home/alex/git/fah-control/fah/__init__.py", line 22, in <module>
    import util
ModuleNotFoundError: No module named 'util'
```

This is on Fedora 31, freshly `git clone`'d repo. I think this error is related to this issue. I couldn't find any workarounds for this, does anyone know of anything I could try?

**Comment by Nindaleth** [comment]
@eiglow Not an answer to your exact question, but it may still help - I'm on Fedora 31 and after changing the first line of `/usr/bin/FAHControl` to `#!/usr/bin/python2
`, I can use the official .rpm packages without any issues.

**Comment by fenixnet-net** [comment]
I'm one of the people showing up to say "yup, doesn't work." The docs mentioned above still claim installing this package will work, and alas that's no longer the case.

What's particularly interesting for me is that I'm running Ubuntu 16.04.6 with system default Python 2.7.12 and it still blows up for me.

`Traceback (most recent call last):
  File "/usr/bin/FAHControl", line 25, in <module>
    from fah import FAHControl, load_fahcontrol_db
ImportError: No module named fah`

An update to the documentation seems wise at this point. The above suggestion of updating the shebang to call python2 directly didn't work for me, as system python is already python 2.7.

**Comment by Nindaleth** [comment]
@fenixnet-net Sorry for being unclear, I posted it as a personally tested workaround that specifically targets Fedora 31. I didn't mean it to be any more ambitious than that :-)

**Comment by bhack** [comment]
See also https://github.com/FoldingAtHome/fah-control/pull/56

**Comment by nikolaik** [comment]
> FYI, a new client is in the works that will solve this.

@jcoffland Can you share a bit more detail on this? Is it a new gtk based client, a rewrite in another cross platfrom native toolkit or [fah-web-client](https://github.com/FoldingAtHome/fah-web-client)?

**Comment by ignaciocaamanio** [comment]
Hello, is there a way to contribute to porting to Python 3? I'm browsing the repository and it's not clear to me.

**Comment by shorttack** [comment]
Try the Linux beta at [https://foldingathome.org/beta/](url) and report success or failure here, please.
_Issue Support_

**Comment by ttepatti** [comment]
I tried installing the beta client, but it still requires the package python-gnome2 which isn't available through the Debian apt repositories on amd64 Debian 10 (buster).

**Comment by Nindaleth** [comment]
@shorttack tried the beta 7.6.8 RPMs on Fedora 31. FAHControl works properly after I manually switch the hashbang to python**2**, otherwise it won't start.

I appreciate the new option to get COVID-19 work units only.

Also looking forward to the goodness from #56 :-)

**Comment by cdberkstresser** [comment]
@Nindaleth  We do have rpms and debs for PR #70, which is definitely a work in progress. It is what I've used to do the beta testing for FAHClient from Ubuntu 20.04 when I needed FAHControl to see what was going on.  Especially handy if you're an early adopter of Ubuntu 20.04.
https://github.com/cdberkstresser/fah-control/releases

**Comment by e-alfred** [comment]
I tried to run the prerelease 7.7.0 client on Ubuntu 20.04 and it worked well after a first start for a while, but now if I try to start it this error message is shown:

```
Traceback (most recent call last):
  File "/usr/bin/FAHControl", line 77, in <module>
    app = FAHControl(glade_data)
  File "/usr/lib/python3/dist-packages/fah/FAHControl.py", line 158, in __init__
    SingleAppServer.__init__(self)
  File "/usr/lib/python3/dist-packages/fah/util/SingleApp.py", line 53, in __init__
    self.check_for_instance()
  File "/usr/lib/python3/dist-packages/fah/util/SingleApp.py", line 72, in check_for_instance
    sock.send('PING')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by cdberkstresser** [comment]
I can replicate that problem when FAHControl is already running (or thinks it is already running).  Can you `killall FAHControl` and try it again.  We should probably add a check to make sure FAHControl isn't already running upon launch.

**Comment by e-alfred** [comment]
@cdberkstresser Thanks, this worked, another problem is the missing application launcher in Ubuntu 20.04 at least.

**Comment by Nindaleth** [comment]
I confirm the launcher absence on Fedora 31, too.

**Comment by ej220** [comment]
I too have bumped into a dead end, Ubuntu 18.04 LTS, with the latest beta version from https://foldingathome.org/beta/:

`$ wget https://download.foldingathome.org/releases/beta/release/fahcontrol/debian-stable-64bit/v7.6/fahcontrol_7.6.13-1_all.deb
$ sudo dpkg -i --force-depends fahcontrol_7.6.13-1_all.deb`

This completes no problem, but I get the `No module named 'fah'` error:

`$ FAHControl
Traceback (most recent call last):
  File "/usr/bin/FAHControl", line 25, in <module>
    from fah import FAHControl, load_fahcontrol_db
ModuleNotFoundError: No module named 'fah'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

**Original exception was:
Traceback (most recent call last):
  File "/usr/bin/FAHControl", line 25, in <module>
    from fah import FAHControl, load_fahcontrol_db
ModuleNotFoundError: No module named 'fah'**
`

**Comment by EnerGeh** [comment]
Beta client is working for me on Ubuntu 20.04. Maybe someone needs my quick'n'dirty desktop-file for FAHControl, feel free to copy and paste it to `/usr/share/applications/FAHControl.desktop` or simply edit your `FAHWebControl.desktop` entry in the same folder.

> [Desktop Entry]
> Name=Folding@home Control
> Exec=FAHControl
> Icon=FAHClient.png
> Type=Application
> Categories=Education;Science;Biology;

**Comment by Dygear** [comment]
Using this https://github.com/FoldingAtHome/fah-control/issues/20#issuecomment-621462602 and this https://github.com/FoldingAtHome/fah-control/issues/20#issuecomment-624788084 and using the current official release of fahclient_7.6.13_amd64.deb and fahviewer_7.6.13_amd64.deb, everything is working well for me. (Except for my Radeon VII not being detected as a target, but that's a whole other issue -- Not in scope of this discussion.)

**Comment by cornuwel** [comment]
Maybe I'm missing something but fahcontrol_7.6.13 still won't install on Ubuntu 20.04:
```
julien@desk-tux ~/Downloads ➜ sudo dpkg -i --force-depends fahcontrol_7.6.13-1_all.deb
(Reading database ... 176630 files and directories currently installed.)
Preparing to unpack fahcontrol_7.6.13-1_all.deb ...
Unpacking fahcontrol (7.6.13-1) over (7.6.13-1) ...
dpkg: fahcontrol: dependency problems, but configuring anyway as you requested:
 fahcontrol depends on python; however:
  Package python is not installed.
 fahcontrol depends on python-gtk2 | python-gnome2; however:
  Package python-gtk2 is not installed.
  Package python-gnome2 is not installed.

Setting up fahcontrol (7.6.13-1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu2) ...
Processing triggers for mime-support (3.64ubuntu1) ...
julien@desk-tux ~/Downloads ➜
```

And the packages in question are nowhere to be found:
```
julien@desk-tux ~/Downloads ➜ sudo apt install python python-gtk2 python-gnome2 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'python-is-python2' instead of 'python'
Package python-gtk2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python-gnome2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-gtk2' has no installation candidate
E: Package 'python-gnome2' has no installation candidate
julien@desk-tux ~/Downloads ➜
```

```
julien@desk-tux ~/Downloads ➜ sudo apt-get -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  fahcontrol
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 1 339 kB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 176630 files and directories currently installed.)
Removing fahcontrol (7.6.13-1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu2) ...
julien@desk-tux ~/Downloads ➜ 
```

**Comment by ffissore** [comment]
fah control won't install on ubuntu 20 due to it still being bound to python 2, which is not available/installed on latest ubuntu (and fedora)
There's an ongoing effort to port fahcontrol to python3: https://github.com/FoldingAtHome/fah-control/pull/70: please join us in testing it and report any issues you find

**Comment by XYchromosone** [comment]
I found this fix for installing the latest package installer version of folding@home [currently fahcontrol_7.6.13-1_all.deb from https://foldingathome.org] on Ubuntu-Studio 20.04, which previously failed to install only the web control package [the viewer and client packages installed OK, though] due to missing dependencies:

https://www.reddit.com/r/Folding/comments/g87e3s/solution_to_fahcontrol_issues_in_ubuntu_2004/

It might help someone else who is having similar issues as I did. It might also help with other installation issues?

**Comment by FreeTheSmoke** [comment]
> I found this fix for installing the latest package installer version of folding@home [currently fahcontrol_7.6.13-1_all.deb from https://foldingathome.org] on Ubuntu-Studio 20.04, which previously failed to install only the web control package [the viewer and client packages installed OK, though] due to missing dependencies:
> 
> https://www.reddit.com/r/Folding/comments/g87e3s/solution_to_fahcontrol_issues_in_ubuntu_2004/
> 
> It might help someone else who is having similar issues as I did. It might also help with other installation issues?

Thanks @XYchromosone I had done something like this a few months ago but my client stopped working after a 'tidy up' of old packages and the info in the link got me straight back to folding. (Ubuntu 20.04 Kernel 5.7.4)

**Comment by XYchromosone** [comment]
> > I found this fix for installing the latest package installer version of folding@home [currently fahcontrol_7.6.13-1_all.deb from https://foldingathome.org] on Ubuntu-Studio 20.04, which previously failed to install only the web control package [the viewer and client packages installed OK, though] due to missing dependencies:
> > https://www.reddit.com/r/Folding/comments/g87e3s/solution_to_fahcontrol_issues_in_ubuntu_2004/
> > It might help someone else who is having similar issues as I did. It might also help with other installation issues?
> 
> Thanks @XYchromosone I had done something like this a few months ago but my client stopped working after a 'tidy up' of old packages and the info in the link got me straight back to folding. (Ubuntu 20.04 Kernel 5.7.4)

@FreeTheSmoke Unusually, although the f@hcontrol installed after following the above, it would not run properly. I ran it overnight in Ubuntu-Studio 20.04 and did not gain any working points, although the web control panel was saying it was connected and folding [set to "While I'm working]?  However, running F@H in Windows it runs fine and my points increase as it should. So I don't know why it's not doing the same in Ubuntu-Studio 20.04?  Hoping someone can help.

**Comment by XYchromosone** [comment]
> Thanks @XYchromosone I had done something like this a few months ago but my client stopped working after a 'tidy up' of old packages and the info in the link got me straight back to folding. (Ubuntu 20.04 Kernel 5.7.4)

@FreeTheSmoke glad it got you up and running. I just can not seem to get any folding happening via web control. although everything seems to have installed ok with F@H viewer, control and client. Hoe are you running F@H CLI or web control? Do you have any tips to get F@H to begin folding on ubuntu 20.04? Anyone? Big TIA for nay help guys

**Comment by FreeTheSmoke** [comment]
You mentioned CLI and web control, but are you aware that this has a GUI too? I think thats the easiest option.

I have 2 machines set up on my home network, I use FAHControl so I can control both instances from whichever machine I am presently on. Although I spent considerable time setting up all the ports and firewall stuff I could only ever get web control to work for the local instance.

Regarding the points: New installs seem to default to "_anonymous_" user so you need to enter your username, passkey, and (optionally) your team number to get the credit.

**Comment by XYchromosone** [comment]
> You mentioned CLI and web control, but are you aware that this has a GUI too? I think thats the easiest option.
> 
> I have 2 machines set up on my home network, I use FAHControl so I can control both instances from whichever machine I am presently on. Although I spent considerable time setting up all the ports and firewall stuff I could only ever get web control to work for the local instance.
> 
> Regarding the points: New installs seem to default to "_anonymous_" user so you need to enter your username, passkey, and (optionally) your team number to get the credit.

**Comment by XYchromosone** [comment]
@FreeTheSmoke  if you mean the web interface as the GUI for f@h on Ubuntu 20.04 then I am using this feature to try and get any folding started, but without any success so far. It just appears to be stalled. I'm using a username and a team number for team fahEVGA everything installed correctly in both Windows 10 x64 and ubuntu-studio 20.04 x64. Windows version has been working fine, though. I'll keep perseverance and hopefully get this problem resolved. As always any help is appreciated by all of you  king and generous loop folks

**Comment by DanielJoyce** [comment]
EOL has been ten years coming, and people still haven't ported to python 3. I was gonna run this, but no progress has been made. Even after two-three years of EOL warnings. :/

**Comment by gaubitzer** [comment]
It is really a shame that this could not be done yet! Especially looking at the hugely increased number of folders since last year.

**Comment by matei-dragu** [comment]
Guys - there are 2 separate PRs open for migrating to Python 3.x and GTK3 - any chance you could ... you know, have a look at them and maybe merge one? I hope it's pretty obvious why I am asking this.

**Comment by PeterDaveHello** [comment]
It's frustrating that this issue has been almost 5 years but still no official update on it, Ubuntu 22.04 is coming now 😅

**Comment by dekaikiwi** [comment]
It's frustrating that anyone moving to Ubuntu now won't be able to use FAH without manually installing deprecated py2 dependencies. Hope there's movement on this issue sometime soon.

**Comment by jwesterd-redhat** [comment]
The RHEL 8 AppStream Lifecycle Page puts the end date of RHEL 8's Python
2.7 package at June 2024.

John Westerdale
